
Ext.onReady(function(){
	Ext.create('Ext.panel.Panel',{
		width:500,
		height:500,
		title:'grid panel',
		renderTo:Ext.getBody(),
		layout:'fit',
		items:[{
			xtype:'grid',
			columns:[{
				text:'a',
				flex:1
			},{
				text:'b',
				flex:1
			},{
				text:'c',
				flex:1
			}],
			tbar:[{
				xtype:'button',
				text:'tbtn'
			}],
			bbar:[{
				xtype:'button',
				text:'bbtn'
			}],
			lbar:[{
				xtype:'button',
				text:'lbtn'
			}],
			rbar:[{
				xtype:'button',
				text:'rbtn'
			}],
			fbar:[{
				xtype:'button',
				text:'fbtn'
			}]
		}]
	})
})