
Ext.onReady(function(){
	Ext.create('Ext.panel.Panel',{
		width:500,
		height:500,
		title:'tree panel',
		renderTo:Ext.getBody(),
		items:[{
			xtype:'treepanel',
			root:{
				text:'Servers',
				expanded:false,
				children:[{
					text:'.settings',
					expanded:true,
					children:[{
						text:'file1',
						leaf:true
					}]
				},{
					text:'.tomcat'
				},{
					text:'.project',
					leaf:true
				}]
			}
		}]
	})
})